esp_video/test_apps/posix:
  enable:
    - if: IDF_TARGET in ["esp32p4", "esp32s3", "esp32c3", "esp32c5", "esp32c6", "esp32c61"]
  depends_components:
    - esp_video
    - esp_cam_sensor
    - esp_sccb_intf