DEFAULT:
    # These formatting options will be used by default
    options: "--style=otbs --attach-namespaces --attach-classes --indent=spaces=4 --convert-tabs --align-pointer=name --align-reference=name --keep-one-line-statements --pad-header --pad-oper"

code_to_ignore_for_now:
    # Ignore files in some other directories
    check: false
    include:
      - "esp_video/include/linux/"
